# Generated by Django 3.1.7 on 2021-05-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0002_auto_20210511_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivemodels',
            name='crypto',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
