# Generated by Django 3.1.7 on 2021-05-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0003_interactivemodels_crypto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivemodels',
            name='companycode',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
