# Generated by Django 3.1.7 on 2021-05-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0004_auto_20210512_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactivemodels',
            name='companycode',
        ),
    ]
