# Generated by Django 3.1.7 on 2021-05-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0005_remove_interactivemodels_companycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksCompanyModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companycode', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
