# Generated by Django 3.1.7 on 2021-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0006_stockscompanymodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockscompanymodels',
            name='companycode',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
