# Generated by Django 3.1.7 on 2021-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0007_auto_20210522_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockscompanymodels',
            name='companycode',
            field=models.CharField(default='GOOG', max_length=1000),
        ),
    ]
