# Generated by Django 3.0.5 on 2021-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0008_auto_20210522_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockscompanymodels',
            name='companycode',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
